[general]
import = [
  # Theme
  # "/home/ojs/.config/alacritty/themes/alacritty-theme/themes/dracula.toml",
]

[window]
# opacity = 1
opacity = 0.90

# padding = { x = 3, y = 3 }

decorations = "None"

# font
[font]
size = 12.0

normal = { family = "DepartureMono Nerd Font" }

[cursor]
style = { shape="Block", blinking = "On" }

blink_interval = 500

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[env]
TERM = "xterm-256color"
